import { join } from 'node:path';

import type { HarnessModule, HarnessContext, HarnessOutput } from './types.js';

export const ciPipelineHarness: HarnessModule = {
  name: 'ci-pipeline',
  displayName: 'CI Pipeline',
  description: 'Generates risk-tiered CI/CD pipeline workflows',
  order: 6,

  isApplicable(): boolean {
    return true;
  },

  async execute(ctx: HarnessContext): Promise<HarnessOutput> {
    const snap = ctx.fileWriter.snapshot();
    const d = ctx.detection;

    const testCmd = d.testCommand ?? 'npm test';
    const lintCmd = d.lintCommand ?? 'npm run lint';
    const buildCmd = d.buildCommand ?? 'npm run build';
    const nodeVersion = '22';

    // ── 1. CI workflow ──────────────────────────────────────────────────
    await ctx.fileWriter.write(
      join(ctx.repoRoot, '.github/workflows/ci.yml'),
      buildCiWorkflow(testCmd, lintCmd, buildCmd, nodeVersion),
    );

    // ── 2. Structural tests workflow ────────────────────────────────────
    await ctx.fileWriter.write(
      join(ctx.repoRoot, '.github/workflows/structural-tests.yml'),
      buildStructuralTestsWorkflow(),
    );

    // ── 3. Harness smoke workflow ───────────────────────────────────────
    await ctx.fileWriter.write(
      join(ctx.repoRoot, '.github/workflows/harness-smoke.yml'),
      buildHarnessSmokeWorkflow(),
    );

    // ── 4. Structural tests shell script ────────────────────────────────
    await ctx.fileWriter.write(
      join(ctx.repoRoot, 'scripts/structural-tests.sh'),
      buildStructuralTestsScript(),
    );

    const diff = ctx.fileWriter.diffSince(snap);

    const output: HarnessOutput = {
      harnessName: 'ci-pipeline',
      filesCreated: diff.created,
      filesModified: diff.modified,
      metadata: {
        ciWorkflowPath: '.github/workflows/ci.yml',
        structuralTestsPath: '.github/workflows/structural-tests.yml',
        harnessSmokePath: '.github/workflows/harness-smoke.yml',
      },
    };

    ctx.previousOutputs.set('ci-pipeline', output);

    return output;
  },
};

// ── File builders ─────────────────────────────────────────────────────────

function buildCiWorkflow(
  testCmd: string,
  lintCmd: string,
  buildCmd: string,
  nodeVersion: string,
): string {
  const lines = [
    'name: CI',
    '',
    'on:',
    '  pull_request:',
    '    types: [opened, synchronize, reopened]',
    '  push:',
    '    branches: [main]',
    '  workflow_dispatch:',
    '    inputs:',
    '      pr_number:',
    "        description: 'PR number to run CI for (used by implementer agent)'",
    '        required: true',
    '        type: string',
    '',
    'permissions:',
    '  contents: read',
    '  pull-requests: read',
    '',
    'concurrency:',
    '  group: ci-${{ github.event.pull_request.number || inputs.pr_number || github.ref }}',
    '  cancel-in-progress: true',
    '',
    'jobs:',
    '  # ============================================================================',
    '  # Preflight — classifies the PR by risk tier and computes required checks.',
    "  # All downstream jobs gate on this job's outputs.",
    '  # For push events (post-merge), defaults to Tier 2 with standard checks.',
    '  # ============================================================================',
    '  risk-gate:',
    '    name: Risk Policy Gate',
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 5',
    '    outputs:',
    '      sha: ${{ steps.pr-gate.outputs.sha || steps.push-gate.outputs.sha }}',
    '      tier: ${{ steps.pr-gate.outputs.tier || steps.push-gate.outputs.tier }}',
    '      tier-name: ${{ steps.pr-gate.outputs.tier-name || steps.push-gate.outputs.tier-name }}',
    '      required-checks: ${{ steps.pr-gate.outputs.required-checks || steps.push-gate.outputs.required-checks }}',
    '      docs-drift: ${{ steps.pr-gate.outputs.docs-drift || steps.push-gate.outputs.docs-drift }}',
    '      review-agent-status: ${{ steps.pr-gate.outputs.review-agent-status || steps.push-gate.outputs.review-agent-status }}',
    '    steps:',
    '      - name: Resolve PR context',
    '        id: pr-context',
    "        if: github.event_name == 'workflow_dispatch'",
    '        env:',
    '          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
    '        run: |',
    '          PR_JSON=$(gh pr view "${{ inputs.pr_number }}" --repo "${{ github.repository }}" --json headRefOid,baseRefName)',
    '          echo "head-sha=$(echo "$PR_JSON" | jq -r \'.headRefOid\')" >> "$GITHUB_OUTPUT"',
    '          echo "base-ref=$(echo "$PR_JSON" | jq -r \'.baseRefName\')" >> "$GITHUB_OUTPUT"',
    '',
    '      - name: Checkout at verified SHA',
    '        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2',
    '        with:',
    '          ref: ${{ steps.pr-context.outputs.head-sha || github.event.pull_request.head.sha || github.sha }}',
    '          fetch-depth: 0',
    '',
    '      - name: Run risk policy gate (PR)',
    "        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'",
    '        id: pr-gate',
    '        run: bash scripts/risk-policy-gate.sh',
    '        env:',
    '          EXPECTED_SHA: ${{ steps.pr-context.outputs.head-sha || github.event.pull_request.head.sha }}',
    '          BASE_REF: ${{ steps.pr-context.outputs.base-ref || github.event.pull_request.base.ref }}',
    '          STRICTNESS: relaxed',
    '',
    '      - name: Set defaults (push to main)',
    "        if: github.event_name == 'push'",
    '        id: push-gate',
    '        run: |',
    '          {',
    '            echo "sha=${{ github.sha }}"',
    '            echo "tier=2"',
    '            echo "tier-name=medium"',
    '            echo \'required-checks=["lint","type-check","test","build","structural-tests","harness-smoke"]\'',
    '            echo "docs-drift=false"',
    '            echo "review-agent-status=skipped"',
    '          } >> "$GITHUB_OUTPUT"',
    '',
    '      - name: Annotate PR with tier',
    "        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'",
    '        run: |',
    '          echo "### Risk Policy Gate" >> "$GITHUB_STEP_SUMMARY"',
    '          echo "" >> "$GITHUB_STEP_SUMMARY"',
    '          echo "| Field | Value |" >> "$GITHUB_STEP_SUMMARY"',
    '          echo "|-------|-------|" >> "$GITHUB_STEP_SUMMARY"',
    '          echo "| **Tier** | ${{ steps.pr-gate.outputs.tier }} (${{ steps.pr-gate.outputs.tier-name }}) |" >> "$GITHUB_STEP_SUMMARY"',
    '          echo "| **SHA** | \\`${{ steps.pr-gate.outputs.sha }}\\` |" >> "$GITHUB_STEP_SUMMARY"',
    '          echo "| **Docs Drift** | ${{ steps.pr-gate.outputs.docs-drift }} |" >> "$GITHUB_STEP_SUMMARY"',
    '          echo "" >> "$GITHUB_STEP_SUMMARY"',
    '          echo "<details><summary>Required Checks</summary>" >> "$GITHUB_STEP_SUMMARY"',
    '          echo "" >> "$GITHUB_STEP_SUMMARY"',
    '          echo \'```json\' >> "$GITHUB_STEP_SUMMARY"',
    '          echo \'${{ steps.pr-gate.outputs.required-checks }}\' >> "$GITHUB_STEP_SUMMARY"',
    '          echo \'```\' >> "$GITHUB_STEP_SUMMARY"',
    '          echo "</details>" >> "$GITHUB_STEP_SUMMARY"',
    '',
    '  # ============================================================================',
    '  # Downstream jobs — gated by risk tier via contains() on required-checks.',
    '  # ============================================================================',
    '',
    '  lint:',
    '    name: Lint',
    '    needs: risk-gate',
    "    if: contains(fromJSON(needs.risk-gate.outputs.required-checks), 'lint')",
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 10',
    '    steps:',
    '      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2',
    '        with:',
    '          ref: ${{ needs.risk-gate.outputs.sha }}',
    '',
    '      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0',
    '        with:',
    `          node-version: ${nodeVersion}`,
    '          cache: npm',
    '',
    '      - run: npm ci',
    `      - run: ${lintCmd}`,
    '',
    '  type-check:',
    '    name: Type Check',
    '    needs: risk-gate',
    "    if: contains(fromJSON(needs.risk-gate.outputs.required-checks), 'type-check')",
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 10',
    '    steps:',
    '      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2',
    '        with:',
    '          ref: ${{ needs.risk-gate.outputs.sha }}',
    '',
    '      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0',
    '        with:',
    `          node-version: ${nodeVersion}`,
    '          cache: npm',
    '',
    '      - run: npm ci',
    '      - run: npm run typecheck',
    '',
    '  test:',
    '    name: Test',
    '    needs: risk-gate',
    "    if: contains(fromJSON(needs.risk-gate.outputs.required-checks), 'test')",
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 20',
    '    steps:',
    '      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2',
    '        with:',
    '          ref: ${{ needs.risk-gate.outputs.sha }}',
    '',
    '      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0',
    '        with:',
    `          node-version: ${nodeVersion}`,
    '          cache: npm',
    '',
    '      - run: npm ci',
    '',
    '      - name: Run tests',
    `        run: ${testCmd}`,
    '',
    '  build:',
    '    name: Build',
    '    needs: risk-gate',
    "    if: contains(fromJSON(needs.risk-gate.outputs.required-checks), 'build')",
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 15',
    '    steps:',
    '      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2',
    '        with:',
    '          ref: ${{ needs.risk-gate.outputs.sha }}',
    '',
    '      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0',
    '        with:',
    `          node-version: ${nodeVersion}`,
    '          cache: npm',
    '',
    '      - run: npm ci',
    `      - run: ${buildCmd}`,
    '',
    '  structural-tests:',
    '    name: Structural Tests',
    '    needs: risk-gate',
    "    if: contains(fromJSON(needs.risk-gate.outputs.required-checks), 'structural-tests')",
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 10',
    '    steps:',
    '      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2',
    '        with:',
    '          ref: ${{ needs.risk-gate.outputs.sha }}',
    '',
    '      - name: Validate architectural boundaries',
    '        run: bash scripts/structural-tests.sh',
    '',
    '  harness-smoke:',
    '    name: Harness Smoke',
    '    needs: risk-gate',
    "    if: contains(fromJSON(needs.risk-gate.outputs.required-checks), 'harness-smoke')",
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 5',
    '    steps:',
    '      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2',
    '        with:',
    '          ref: ${{ needs.risk-gate.outputs.sha }}',
    '',
    '      - name: Validate harness.config.json',
    '        run: |',
    '          node -e "',
    "            const fs = require('fs');",
    "            const config = JSON.parse(fs.readFileSync('harness.config.json', 'utf8'));",
    "            const required = ['version', 'riskTiers', 'commands', 'shaDiscipline', 'architecturalBoundaries'];",
    '            const missing = required.filter(k => !(k in config));',
    "            if (missing.length) { console.error('Missing keys:', missing.join(', ')); process.exit(1); }",
    "            for (const t of ['tier1', 'tier2', 'tier3']) {",
    "              if (!config.riskTiers[t]) { console.error('Missing tier:', t); process.exit(1); }",
    '            }',
    "            console.log('✔ harness.config.json schema valid');",
    '          "',
    '',
    '      - name: Check CLAUDE.md',
    '        run: |',
    '          if [[ ! -s CLAUDE.md ]]; then',
    '            echo "::error::CLAUDE.md is missing or empty"',
    '            exit 1',
    '          fi',
    '          echo "✔ CLAUDE.md present ($(wc -l < CLAUDE.md) lines)"',
    '',
    '      - name: Check critical files',
    '        run: |',
    '          files=(',
    '            src/index.ts src/cli.ts package.json tsconfig.json',
    '            tsup.config.ts vitest.config.ts eslint.config.js harness.config.json',
    '          )',
    '          for f in "${files[@]}"; do',
    '            if [[ ! -f "$f" ]]; then',
    '              echo "::error::Missing: $f"',
    '              exit 1',
    '            fi',
    '          done',
    '          echo "✔ All critical files present"',
    '',
    '      - name: Check workflow files',
    '        run: |',
    '          for f in .github/workflows/ci.yml .github/workflows/structural-tests.yml .github/workflows/harness-smoke.yml; do',
    '            if [[ ! -f "$f" ]]; then',
    '              echo "::error::Missing workflow: $f"',
    '              exit 1',
    '            fi',
    '          done',
    '          echo "✔ All workflow files present"',
    '',
    '      - name: Check PR template',
    '        run: |',
    '          if [[ -f templates/pr-template.md ]] || [[ -f .github/PULL_REQUEST_TEMPLATE.md ]]; then',
    '            echo "✔ PR template present"',
    '          else',
    '            echo "::warning::No PR template found"',
    '          fi',
    '',
    '      - name: Validate harness commands',
    '        run: |',
    '          node -e "',
    "            const config = JSON.parse(require('fs').readFileSync('harness.config.json', 'utf8'));",
    "            const pkg = JSON.parse(require('fs').readFileSync('package.json', 'utf8'));",
    '            const cmds = config.commands || {};',
    '            for (const [key, cmd] of Object.entries(cmds)) {',
    "              const bin = cmd.split(' ')[0];",
    '              const inScripts = pkg.scripts && Object.values(pkg.scripts).some(s => s.includes(bin));',
    "              console.log(inScripts ? '✔' : '⚠', key + ':', cmd, inScripts ? '(found)' : '(not in scripts — may be devDep binary)');",
    '            }',
    '          "',
    '',
    '  manual-approval:',
    '    name: Manual Approval (Tier 3)',
    '    needs: risk-gate',
    "    if: contains(fromJSON(needs.risk-gate.outputs.required-checks), 'manual-approval')",
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 1440',
    '    environment: tier3-approval',
    '    steps:',
    '      - name: Tier 3 change detected',
    '        run: |',
    '          echo "::warning::This PR touches critical paths and requires manual approval."',
    '          echo "A maintainer must approve the \'tier3-approval\' environment to proceed."',
    '          echo ""',
    '          echo "Changed tier-3 files are listed in the Risk Policy Gate summary."',
  ];
  return lines.join('\n') + '\n';
}

function buildStructuralTestsWorkflow(): string {
  const lines = [
    'name: Structural Tests',
    '',
    'on:',
    '  workflow_dispatch:',
    '  workflow_call:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  structural-tests:',
    '    name: Architectural Boundary Validation',
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 10',
    '    steps:',
    '      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2',
    '',
    '      - name: Validate architectural boundaries',
    '        run: bash scripts/structural-tests.sh',
    '',
    '      - name: Validate import-type discipline',
    '        run: |',
    '          echo "Checking for value imports of type-only symbols..."',
    '          violations=0',
    "          while IFS= read -r -d '' file; do",
    "            # Flag imports from known type-only files that don't use 'import type'",
    '            if grep -Pn "^import\\s+\\{[^}]+\\}\\s+from\\s+[\'\\"].*types[\'\\"]" "$file" | grep -v "import type" > /dev/null 2>&1; then',
    '              echo "::warning file=${file#./}::Possible missing \'import type\' for types-only module"',
    '            fi',
    "          done < <(find src -name '*.ts' -type f -print0)",
    '          echo "✔ Import-type discipline check complete"',
    '',
    '      - name: Verify no circular imports',
    '        run: |',
    '          echo "Scanning for obvious circular import patterns..."',
    '          # Check that utils/ never imports from any sibling module',
    '          if grep -rE "from\\s+[\'\\"]\\.\\.\\/(commands|core|harnesses|prompts|providers|ui)\\/" src/utils/ 2>/dev/null; then',
    '            echo "::error::utils/ must not import from sibling modules"',
    '            exit 1',
    '          fi',
    '          # Check that core/ only imports from utils/',
    '          if grep -rE "from\\s+[\'\\"]\\.\\.\\/(commands|harnesses|prompts|providers|ui)\\/" src/core/ 2>/dev/null; then',
    '            echo "::error::core/ must only import from utils/"',
    '            exit 1',
    '          fi',
    '          # Check that ui/ only imports from utils/',
    '          if grep -rE "from\\s+[\'\\"]\\.\\.\\/(commands|core|harnesses|prompts|providers)\\/" src/ui/ 2>/dev/null; then',
    '            echo "::error::ui/ must only import from utils/"',
    '            exit 1',
    '          fi',
    '          echo "✔ No circular import patterns detected"',
  ];
  return lines.join('\n') + '\n';
}

function buildHarnessSmokeWorkflow(): string {
  const lines = [
    'name: Harness Smoke Tests',
    '',
    'on:',
    '  workflow_dispatch:',
    '  workflow_call:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  harness-smoke:',
    '    name: Harness Smoke Tests',
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 5',
    '    steps:',
    '      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2',
    '',
    '      - name: Validate harness.config.json schema',
    '        run: |',
    '          node -e "',
    "            const fs = require('fs');",
    "            const config = JSON.parse(fs.readFileSync('harness.config.json', 'utf8'));",
    '',
    '            // Check top-level required keys',
    "            const required = ['version', 'riskTiers', 'commands', 'shaDiscipline', 'architecturalBoundaries'];",
    '            const missing = required.filter(k => !(k in config));',
    '            if (missing.length) {',
    "              console.error('Missing required keys:', missing.join(', '));",
    '              process.exit(1);',
    '            }',
    '',
    '            // Check all three risk tiers exist',
    "            for (const tier of ['tier1', 'tier2', 'tier3']) {",
    '              if (!config.riskTiers[tier]) {',
    "                console.error('Missing risk tier:', tier);",
    '                process.exit(1);',
    '              }',
    '              const t = config.riskTiers[tier];',
    '              if (!t.patterns || !Array.isArray(t.patterns)) {',
    "                console.error(tier + ' missing patterns array');",
    '                process.exit(1);',
    '              }',
    '              if (!t.requiredChecks || !Array.isArray(t.requiredChecks)) {',
    "                console.error(tier + ' missing requiredChecks array');",
    '                process.exit(1);',
    '              }',
    '            }',
    '',
    '            // Check SHA discipline',
    "            if (typeof config.shaDiscipline.enforceExactSha !== 'boolean') {",
    "              console.error('shaDiscipline.enforceExactSha must be boolean');",
    '              process.exit(1);',
    '            }',
    '',
    '            // Check architectural boundaries',
    '            const modules = Object.keys(config.architecturalBoundaries);',
    '            if (modules.length === 0) {',
    "              console.error('architecturalBoundaries must define at least one module');",
    '              process.exit(1);',
    '            }',
    '',
    "            console.log('✔ harness.config.json schema valid (' + modules.length + ' modules, 3 tiers)');",
    '          "',
    '',
    '      - name: Validate harness commands exist',
    '        run: |',
    '          node -e "',
    "            const config = JSON.parse(require('fs').readFileSync('harness.config.json', 'utf8'));",
    "            const pkg = JSON.parse(require('fs').readFileSync('package.json', 'utf8'));",
    '            const scripts = pkg.scripts || {};',
    '            const cmds = config.commands || {};',
    '            let failures = 0;',
    '',
    '            for (const [key, cmd] of Object.entries(cmds)) {',
    "              const bin = cmd.split(' ')[0];",
    '              const found = Object.values(scripts).some(s => s.includes(bin));',
    '              if (found) {',
    "                console.log('✔', key + ':', cmd);",
    '              } else {',
    "                console.warn('⚠', key + ':', cmd, '(not in package.json scripts)');",
    '              }',
    '            }',
    '',
    '            if (failures > 0) process.exit(1);',
    '          "',
    '',
    '      - name: Check CLAUDE.md',
    '        run: |',
    '          if [[ ! -s CLAUDE.md ]]; then',
    '            echo "::error::CLAUDE.md is missing or empty"',
    '            exit 1',
    '          fi',
    '          echo "✔ CLAUDE.md present ($(wc -l < CLAUDE.md) lines)"',
    '',
    '      - name: Check critical project files',
    '        run: |',
    '          files=(',
    '            src/index.ts src/cli.ts package.json tsconfig.json',
    '            tsup.config.ts vitest.config.ts eslint.config.js harness.config.json',
    '          )',
    '          missing=0',
    '          for f in "${files[@]}"; do',
    '            if [[ ! -f "$f" ]]; then',
    '              echo "::error::Missing: $f"',
    '              ((missing++))',
    '            fi',
    '          done',
    '          if (( missing > 0 )); then',
    '            exit 1',
    '          fi',
    '          echo "✔ All ${#files[@]} critical files present"',
    '',
    '      - name: Check CI workflow files',
    '        run: |',
    '          workflows=(',
    '            .github/workflows/ci.yml',
    '            .github/workflows/structural-tests.yml',
    '            .github/workflows/harness-smoke.yml',
    '          )',
    '          missing=0',
    '          for f in "${workflows[@]}"; do',
    '            if [[ ! -f "$f" ]]; then',
    '              echo "::error::Missing workflow: $f"',
    '              ((missing++))',
    '            fi',
    '          done',
    '          if (( missing > 0 )); then',
    '            exit 1',
    '          fi',
    '          echo "✔ All ${#workflows[@]} workflow files present"',
    '',
    '      - name: Check PR template',
    '        run: |',
    '          if [[ -f templates/pr-template.md ]]; then',
    '            echo "✔ PR template: templates/pr-template.md"',
    '          elif [[ -f .github/PULL_REQUEST_TEMPLATE.md ]]; then',
    '            echo "✔ PR template: .github/PULL_REQUEST_TEMPLATE.md"',
    '          else',
    '            echo "::warning::No PR template found in templates/ or .github/"',
    '          fi',
    '',
    '      - name: Check risk-policy-gate script',
    '        run: |',
    '          if [[ ! -x scripts/risk-policy-gate.sh ]] && [[ ! -f scripts/risk-policy-gate.sh ]]; then',
    '            echo "::error::scripts/risk-policy-gate.sh not found"',
    '            exit 1',
    '          fi',
    '          echo "✔ Risk policy gate script present"',
    '',
    '      - name: Check structural-tests script',
    '        run: |',
    '          if [[ ! -f scripts/structural-tests.sh ]]; then',
    '            echo "::error::scripts/structural-tests.sh not found"',
    '            exit 1',
    '          fi',
    '          echo "✔ Structural tests script present"',
  ];
  return lines.join('\n') + '\n';
}

function buildStructuralTestsScript(): string {
  const lines = [
    '#!/usr/bin/env bash',
    '# ============================================================================',
    '# Structural Tests — Architectural Boundary Validation',
    '#',
    '# Reads architectural boundaries from harness.config.json and validates that',
    '# import dependencies between src/ modules respect the declared rules.',
    '#',
    '# Exit 0: all boundaries respected.',
    '# Exit 1: one or more violations found.',
    '# ============================================================================',
    'set -euo pipefail',
    '',
    'REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"',
    'SRC_DIR="${REPO_ROOT}/src"',
    'CONFIG_FILE="${REPO_ROOT}/harness.config.json"',
    'VIOLATIONS=0',
    '',
    '# ============================================================================',
    '# Step 1: Read boundaries from harness.config.json (single source of truth)',
    '# ============================================================================',
    'if [[ ! -f "$CONFIG_FILE" ]]; then',
    '  echo "::error::harness.config.json not found at ${CONFIG_FILE}"',
    '  exit 1',
    'fi',
    '',
    '# Extract module names and their allowed imports from the config using Node.js',
    'BOUNDARIES_JSON="$(node -e "',
    "  const config = JSON.parse(require('fs').readFileSync('${CONFIG_FILE}', 'utf8'));",
    '  const b = config.architecturalBoundaries || {};',
    '  const out = {};',
    '  for (const [mod, def] of Object.entries(b)) {',
    "    out[mod] = (def.allowedImports || []).join(' ');",
    '  }',
    '  console.log(JSON.stringify(out));',
    '")"',
    '',
    '# Parse into bash associative array',
    'declare -A ALLOWED',
    'MODULES=()',
    '',
    "while IFS='=' read -r key val; do",
    '  ALLOWED["$key"]="$val"',
    '  MODULES+=("$key")',
    'done < <(node -e "',
    '  const b = JSON.parse(process.argv[1]);',
    '  for (const [k, v] of Object.entries(b)) {',
    "    console.log(k + '=' + v);",
    '  }',
    '" "$BOUNDARIES_JSON")',
    '',
    'if (( ${#MODULES[@]} == 0 )); then',
    '  echo "::error::No architectural boundaries found in ${CONFIG_FILE}"',
    '  exit 1',
    'fi',
    '',
    '# ============================================================================',
    '# Step 2: Scan each module for cross-module imports',
    '# ============================================================================',
    'echo "╔═════════════════════════════════════════════════╗"',
    'echo "║     Architectural Boundary Validation            ║"',
    'echo "╚═════════════════════════════════════════════════╝"',
    'echo ""',
    'echo "Boundaries loaded from: harness.config.json (${#MODULES[@]} modules)"',
    'echo ""',
    '',
    'for module in "${MODULES[@]}"; do',
    '  dir="${SRC_DIR}/${module}"',
    '  [[ -d "$dir" ]] || continue',
    '',
    '  allowed="${ALLOWED[$module]}"',
    '  module_violations=0',
    '',
    "  while IFS= read -r -d '' file; do",
    "    # Find lines containing cross-module relative imports: from '../<target>/'",
    '    while IFS= read -r line; do',
    '      target=""',
    '',
    "      # Extract target module from: from '../<module>/...'",
    '      if [[ "$line" =~ from\\ +[\\\'\\"]\\.\\.\\/(a-z]+)/ ]]; then',
    '        target="${BASH_REMATCH[1]}"',
    '      fi',
    '',
    '      [[ -z "$target" ]] && continue',
    '      [[ "$target" == "$module" ]] && continue',
    '',
    '      # Verify target is a known module (skip unknown relative paths)',
    '      is_known=false',
    '      for m in "${MODULES[@]}"; do',
    '        [[ "$target" == "$m" ]] && { is_known=true; break; }',
    '      done',
    '      $is_known || continue',
    '',
    '      # Check if the import is in the allowed list',
    '      if [[ " $allowed " != *" $target "* ]]; then',
    '        rel="${file#"$REPO_ROOT"/}"',
    '        echo "::error file=${rel}::${module}/ cannot import from ${target}/ (allowed: ${allowed:-none})"',
    '        ((VIOLATIONS++))',
    '        ((module_violations++))',
    '      fi',
    '    done < <(grep -E "from\\s+[\'\\"]\\.\\.\\/(" "$file" 2>/dev/null || true)',
    '  done < <(find "$dir" -name \'*.ts\' -type f -print0)',
    '',
    '  if (( module_violations == 0 )); then',
    '    echo "  ✔ ${module}/ → allowed: [${allowed:-none}]"',
    '  else',
    '    echo "  ✘ ${module}/ → ${module_violations} violation(s)"',
    '  fi',
    'done',
    '',
    '# ============================================================================',
    '# Step 3: Report results',
    '# ============================================================================',
    'echo ""',
    'if (( VIOLATIONS > 0 )); then',
    '  echo "✘ Found ${VIOLATIONS} architectural boundary violation(s)"',
    '  echo ""',
    '  echo "To fix: either update the import to use an allowed module, or update"',
    '  echo "architecturalBoundaries in harness.config.json if the dependency is intentional."',
    '  exit 1',
    'else',
    '  echo "✔ All architectural boundaries respected (${#MODULES[@]} modules checked)"',
    'fi',
  ];
  return lines.join('\n') + '\n';
}
