import type { DetectionResult, UserPreferences } from './types.js';

/**
 * Prompt for generating the documentation garbage collection (doc-gardening) system.
 */
export function buildGarbageCollectionPrompt(
  detection: DetectionResult,
  prefs: UserPreferences,
): string {
  return `Generate a documentation garbage collection (doc-gardening) system for this ${detection.primaryLanguage} project. This system runs periodically to detect stale, outdated, or inaccurate documentation and creates PRs to fix it.

## Detected Stack Context

- **Language**: ${detection.primaryLanguage}
- **Framework**: ${detection.framework ?? 'none'}
- **Existing Docs**: ${detection.existingDocs.length > 0 ? detection.existingDocs.join(', ') : 'none'}
- **CI Provider**: ${prefs.ciProvider}
- **Build Command**: \`${detection.buildCommand ?? 'not detected'}\`
- **Test Command**: \`${detection.testCommand ?? 'not detected'}\`
- **Lint Command**: \`${detection.lintCommand ?? 'not detected'}\`

## Files to Generate

### 1. ${prefs.ciProvider === 'github-actions' ? '.github/workflows/doc-gardening.yml' : prefs.ciProvider === 'gitlab-ci' ? '.gitlab-ci.yml (doc-gardening job section)' : 'bitbucket-pipelines.yml (doc-gardening section)'}

A scheduled CI workflow that detects and fixes documentation drift:

${prefs.ciProvider === 'github-actions' ? `\`\`\`yaml
name: Documentation Gardening
on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9am UTC
  workflow_dispatch: {}    # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  gardening:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git log analysis
      - name: Set up environment
        # Set up Node.js/Python/etc. as needed for the project
      - name: Run documentation gardening agent
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          npx claude-code --print "$(cat scripts/doc-gardening-prompt.md)"
      - name: Create PR if changes detected
        uses: peter-evans/create-pull-request@v6
        with:
          title: "docs: weekly documentation gardening"
          body: |
            ## Automated Documentation Gardening

            This PR was generated by the weekly doc-gardening workflow.

            ### Changes include:
            - Updated stale references to renamed/deleted files or functions
            - Fixed broken internal markdown links
            - Synchronized documented commands with actual package.json/pyproject.toml scripts
            - Removed references to deprecated APIs or deleted modules
            - Updated CLAUDE.md if project tooling has changed

            Please review changes carefully before merging.
          branch: docs/weekly-gardening
          commit-message: "docs: automated documentation gardening"
          labels: documentation, automated
          delete-branch: true
\`\`\`` : `Provide an equivalent workflow configuration for ${prefs.ciProvider} that runs weekly and creates merge requests/PRs for documentation fixes.`}

**Workflow behavior:**
- If no documentation changes are needed, the workflow succeeds without creating a PR
- If a gardening PR already exists and is open, update it rather than creating a new one
- The workflow must be idempotent — running it twice produces the same result
- Set a timeout of 15 minutes to prevent runaway agent sessions

### 2. scripts/doc-gardening-prompt.md

The prompt given to Claude Code for the gardening task. This prompt must be specific and thorough:

\`\`\`markdown
# Documentation Gardening Task

Scan this repository for stale, outdated, or inaccurate documentation and fix it.

## Scanning Checklist

### 1. Broken File References
- Search all markdown files for references to source files (backtick paths, links)
- Verify each referenced file still exists at that path
- If a file was moved, update the reference to the new location
- If a file was deleted, remove the reference or replace with a note

### 2. Outdated Commands
- Read the project's build configuration (package.json scripts, pyproject.toml, Makefile, etc.)
- Compare documented commands in CLAUDE.md, README.md, and docs/*.md against actual available commands
- Update any commands that have changed
- Flag commands that exist in docs but not in the project configuration

### 3. Architecture Drift
- Compare docs/architecture.md against the actual directory structure
- Identify components/modules that have been added, renamed, or removed since the docs were last updated
- Update component descriptions, dependency diagrams, and layer definitions

### 4. CLAUDE.md Accuracy
- Verify that CLAUDE.md build/test/lint commands match the project's actual scripts
- Check that listed architectural layers match the real directory structure
- Ensure critical paths listed in CLAUDE.md match harness.config.json
- Validate code style rules against the actual linter/formatter configuration

### 5. Broken Links
- Check all markdown links (both [text](url) and [text][ref] styles)
- For internal links: verify the target file/heading exists
- For external links: note but do not attempt to fix (they may be intentionally external)

### 6. Stale Examples
- Find code examples in documentation that reference imports, functions, or classes
- Verify these still exist in the codebase with the documented signatures
- Update examples if the API has changed

## Rules

- Only modify documentation files (*.md, *.mdx, *.rst)
- NEVER modify source code, configuration files, or CI workflows
- When removing a stale reference, check if there's a replacement to link to
- Preserve the document's overall structure, tone, and formatting
- If unsure about a change, leave a TODO comment rather than guessing
- Add \`<!-- Last gardened: YYYY-MM-DD -->\` to sections you've verified or updated

## Output

After making changes, provide a summary listing:
- Files modified and what was changed
- Issues found and fixed
- Issues found but requiring human decision (leave as TODO comments)
- Sections verified as up-to-date (no changes needed)
\`\`\`

## Workflow Quality Requirements

- The workflow must not make destructive changes to the repository
- All changes must go through a PR — never push directly to main
- The gardening agent should be conservative: only fix issues it's confident about
- If many issues are found, prefer creating a single focused PR over multiple
- The prompt must be specific enough to avoid false positives and unnecessary churn
- Include a manual workflow_dispatch trigger for on-demand gardening
- The workflow should gracefully handle the case where the ANTHROPIC_API_KEY secret is not set

## Output Format

Return the complete file contents for each file, separated by a comment line with the target file path. Do not wrap in markdown code fences.`;
}
